; build.ahk - regenerate HPKeys.ahk's embedded resources and compile HPKeys.exe
;
;   reads:  defaults.ini   -> embedded default configuration (human-readable)
;           HPKeys.ico     -> embedded tray icon (base64)
;           HPKeys.ahk     -> target of the marker-block rewrite
;   then runs Ahk2Exe (Unicode 32-bit base) to produce HPKeys.exe.
;
; Console-aware: when launched from a terminal or CI runner it attaches to the
; parent console, writes progress to stdout, errors to stderr, and exits with
; a nonzero code on failure. When double-clicked it uses dialog boxes instead.
; Stop HPKeys.exe before building - the exe cannot be overwritten while
; running. AutoHotkey v1.1 Unicode required. Run from this directory.
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%
FileEncoding, UTF-8

EnvGet, ghEnv, GITHUB_ACTIONS
global ConMode := DllCall("AttachConsole", "Int", -1) || (ghEnv = "true")   ; ATTACH_PARENT_PROCESS / CI

IniSrc := A_ScriptDir "\defaults.ini"
IcoSrc := A_ScriptDir "\HPKeys.ico"
AhkSrc := A_ScriptDir "\HPKeys.ahk"
ExeOut := A_ScriptDir "\HPKeys.exe"
; /relaunch <pid> <ahk|exe>: invoked by HPKeys' "Rebuild and restart" tray
; item - wait for the caller to exit, rebuild, then restart it (or restart
; the old copy if the build fails).
global RelaunchMode := false, RelaunchTarget := ""
if (A_Args.Length() >= 3 && A_Args[1] = "/relaunch")
{
    RelaunchMode := true
    if (A_Args[3] = "ahk")
        RelaunchTarget := """" A_AhkPath """ """ AhkSrc """"
    else
        RelaunchTarget := """" ExeOut """"
    Process, WaitClose, % A_Args[2] + 0, 15
    if ErrorLevel
        Fail("HPKeys (pid " A_Args[2] ") did not exit within 15s; aborting rebuild.")
    Log("previous instance exited; rebuilding")
}


for i, f in [IniSrc, IcoSrc, AhkSrc]
    if !FileExist(f)
        Fail("Missing file: " f)

; ---- 1. base64 of the icon, chunked to 100-column lines ----------------------
f := FileOpen(IcoSrc, "r")
if !IsObject(f)
    Fail("Cannot open " IcoSrc " for reading.")
icoLen := f.Length
if (icoLen = 0)
    Fail("HPKeys.ico is empty.")
VarSetCapacity(icoRaw, icoLen, 0)
if (f.RawRead(&icoRaw, icoLen) != icoLen)
    Fail("Short read on HPKeys.ico.")
f.Close()
Log("read " IcoSrc " (" icoLen " bytes)")
b64Len := 0
if !DllCall("Crypt32\CryptBinaryToStringA", "Ptr", &icoRaw, "UInt", icoLen, "UInt", 1, "Ptr", 0, "UIntP", b64Len)
    Fail("CryptBinaryToString sizing failed (GLE " A_LastError ").")
VarSetCapacity(b64Buf, b64Len + 16, 0)
if !DllCall("Crypt32\CryptBinaryToStringA", "Ptr", &icoRaw, "UInt", icoLen, "UInt", 1, "Ptr", &b64Buf, "UIntP", b64Len)
    Fail("CryptBinaryToString failed (GLE " A_LastError ").")
b64 := StrReplace(StrReplace(StrGet(&b64Buf, "CP0"), "`r"), "`n")
iconLines := ""
Loop
{
    if (StrLen(b64) <= 100)
    {
        iconLines .= b64
        break
    }
    iconLines .= SubStr(b64, 1, 100) "`n"
    b64 := SubStr(b64, 101)
}
Log("icon encoded: " StrLen(iconLines) " bytes of base64")

; ---- 2. defaults.ini -> quoted continuation block ------------------------------
FileRead, iniText, %IniSrc%
iniText := StrReplace(iniText, "`r`n", "`n")
iniText := StrReplace(iniText, """", """""")          ; " -> ""
iniText := RTrim(iniText, "`r`n")
Loop, Parse, iniText, `n, `r
    if (SubStr(A_LoopField, 1, 1) = ")")
        Fail("defaults.ini has a line starting with a close-paren - cannot embed that safely.")
Log("defaults.ini read (" StrLen(iniText) " chars, quotes escaped)")

iniBlock := ";;@@DEFAULTS_INI_BEGIN - generated by build.ahk from defaults.ini - do not edit`n"
          . "DefaultsIniText() {`n"
          . "    static s := ""`n"
          . "(LTrim`n"
          . iniText "`n"
          . ")""`n"
          . "    return s`n"
          . "}`n"
          . ";;@@DEFAULTS_INI_END"

iconBlock := ";;@@ICON_B64_BEGIN - generated by build.ahk from HPKeys.ico - do not edit`n"
           . "IconB64Text() {`n"
           . "    static s := ""`n"
           . "(LTrim`n"
           . iconLines "`n"
           . ")""`n"
           . "    return s`n"
           . "}`n"
           . ";;@@ICON_B64_END"

; ---- 3. splice into HPKeys.ahk -------------------------------------------------
FileRead, ahkText, %AhkSrc%
newAhk := Splice(ahkText, "DEFAULTS_INI", iniBlock)
newAhk := Splice(newAhk, "ICON_B64", iconBlock)
report := ""
if (newAhk == ahkText)
    report .= "HPKeys.ahk already up to date.`n"
else
{
    newAhk := StrReplace(newAhk, "`r`n", "`n")   ; keep line endings LF
    WriteUtf8(AhkSrc, newAhk)
    report .= "HPKeys.ahk updated (embedded defaults + icon).`n"
}

; ---- 4. compile with Ahk2Exe ----------------------------------------------------
RegRead, instDir, HKLM\SOFTWARE\AutoHotkey, InstallDir
if (ErrorLevel || !FileExist(instDir "\Compiler\Ahk2Exe.exe"))
    SplitPath, A_AhkPath,, instDir
cmp := instDir "\Compiler\Ahk2Exe.exe"
if !FileExist(cmp)
    Fail("Ahk2Exe.exe not found under: " instDir "\Compiler  (install AutoHotkey v1.1 or fix the path).")
base := instDir "\AutoHotkeyU32.exe"
baseOpt := FileExist(base) ? " /base """ base """" : ""
Log("compiling with " cmp)
Run, % """" cmp """ /cp 650001 /in """ AhkSrc """ /out """ ExeOut """ /icon """ IcoSrc """" baseOpt, %A_ScriptDir%, UseErrorLevel, ahkPid
if (UseErrorLevel = "ERROR")
    Fail("Failed to launch Ahk2Exe.")
Process, WaitClose, %ahkPid%, 180
if ErrorLevel
{
    Process, Close, %ahkPid%
    Fail("Ahk2Exe did not finish within 180s (probably showing a dialog on a headless runner); killed.")
}
if !FileExist(ExeOut)
    Fail("Ahk2Exe ran but HPKeys.exe was not produced. Is the old HPKeys.exe still running? Stop it first.")
FileGetSize, exeSize, %ExeOut%
report .= "HPKeys.exe built (" exeSize " bytes, icon source " icoLen " bytes)."
Log(report)
if (!ConMode && !RelaunchMode)
    MsgBox, 64, build, %report%
if RelaunchMode
{
    Log("relaunching " RelaunchTarget)
    Run, % RelaunchTarget, %A_ScriptDir%
}
ExitApp, 0

; --- helpers ----------------------------------------------------------------------

Log(msg) {
    if ConMode
        FileAppend, %msg%`n, *
}

Fail(msg) {
    global RelaunchMode, RelaunchTarget
    if ConMode
        FileAppend, error: %msg%`n, **
    else
        MsgBox, 16, build, %msg%
    if (RelaunchMode && RelaunchTarget != "")
    {
        Log("build failed - relaunching previous copy")
        try Run, % RelaunchTarget, %A_ScriptDir%
    }
    ExitApp, 1
}

; Write text as UTF-8 without BOM, byte-exact: LF stays LF and Ahk2Exe accepts
; the file (FileAppend would translate `n to `r`n in text mode, and a BOM
; breaks Ahk2Exe).
WriteUtf8(path, text) {
    encLen := StrPut(text, "UTF-8") - 1
    VarSetCapacity(buf, encLen)
    StrPut(text, &buf, encLen, "UTF-8")
    f := FileOpen(path, "w")
    if !IsObject(f)
        Fail("Cannot open " path " for writing.")
    f.RawWrite(&buf, encLen)
    f.Close()
}

; Replace the lines between ;;@@<tag>_BEGIN and ;;@@<tag>_END (inclusive) with block.
Splice(text, tag, block) {
    out := "", inBlock := false, found := false
    beg := ";;@@" tag "_BEGIN"
    end := ";;@@" tag "_END"
    Loop, Parse, text, `n, `r
    {
        ln := A_LoopField
        if (SubStr(ln, 1, StrLen(beg)) = beg)
        {
            out .= block "`n"
            inBlock := true, found := true
            continue
        }
        if (inBlock && SubStr(ln, 1, StrLen(end)) = end)
        {
            inBlock := false
            continue
        }
        if !inBlock
            out .= ln "`n"
    }
    if (!found || inBlock)
        Fail("Markers " beg " / " end " missing or unbalanced in HPKeys.ahk.")
    return RTrim(out, "`n")
}
